# Generated by Django 4.1.1 on 2023-03-20 10:52

from django.db import migrations, models
import pins.validators


class Migration(migrations.Migration):

    dependencies = [
        ("pins", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pin",
            name="file",
            field=models.FileField(
                upload_to="pins", validators=[pins.validators.validate_file_size]
            ),
        ),
    ]
